### ISSUE TITLE
[Enhancement] Add repo URL to orb description

### ISSUE THREAD

**Issue by KyleTryon** [Contrast-Security-OSS/contrast-security-orb#1]
Add the GitHub repository to the orb description.
https://github.com/CircleCI-Public/Orb-Policies/blame/master/Orb%20Best%20Practices%20Guidelines.md#L13

_Consider adding the `orbtoberfest` label on this issue to have it appear on our upcoming Hacktoberfest landing page_

**Comment by KyleTryon** [comment]
Personal request: I would also like to see more information in the description that explains about contrast security and for what use-case this orb serves (coming from someone who would not previously be aware of contrast security).

**Comment by sajarin** [comment]
@KyleTryon since we've since moved towards live docs, is this issue still relevant?
