### ISSUE TITLE
[Enhancement] Parameterize executor.

### ISSUE THREAD

**Issue by KyleTryon** [Contrast-Security-OSS/contrast-security-orb#2]
Suggestion from best practice guideline. Consider parameterizing the docker image or tag to protect against potential sudden changes to the hardcoded docker tag.

https://github.com/CircleCI-Public/Orb-Policies/blame/master/Orb%20Best%20Practices%20Guidelines.md#L49

You may also be interested in using CircleCI's new beta images which are highly optimized for speed. https://hub.docker.com/u/cimg

_Consider adding the `orbtoberfest` label on this issue to have it appear on our upcoming Hacktoberfest landing page_

**Comment by lex111** [comment]
I created PR #8.
